// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awwzombzlpogjhstwdmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3d3pvbWJ6bHBvZ2poc3R3ZG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDIzNTgsImV4cCI6MjA2NTk3ODM1OH0.kr8OnrL6wGKMtxJgXGdvhoO3g7R7wEOe39Ni3DT3hto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});